name: Naukri Resume Update

on:
  schedule:
    # Runs at 8:00 AM, 2:00 PM, and 9:00 PM IST daily
    # Note: GitHub Actions uses UTC time, so we need to convert
    # 8:00 AM IST = 2:30 AM UTC
    # 2:00 PM IST = 8:30 AM UTC  
    # 9:00 PM IST = 3:30 PM UTC
    - cron: '30 2,8,15 * * *'
  
  # Optional: Allow manual trigger from GitHub UI
  workflow_dispatch:

jobs:
  update_resume:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager
        
    - name: Install Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Install ChromeDriver
      run: |
        # Let Python and webdriver-manager handle ChromeDriver installation
        python -c "from webdriver_manager.chrome import ChromeDriverManager; ChromeDriverManager().install()"
        
    - name: Install Xvfb (for headless mode)
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        
    - name: Run update script
      env:
        NAUKRI_USERNAME: ${{ secrets.NAUKRI_USERNAME }}
        NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
      run: |
        xvfb-run python ResumeAutomate.py
        
    - name: Upload screenshots as artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: screenshots
        path: |
          *.png