name: Naukri Resume Update

on:
  schedule:
    # Runs at 8:00 AM, 2:00 PM, and 9:00 PM IST daily
    # Note: GitHub Actions uses UTC time, so we need to convert
    # 8:00 AM IST = 2:30 AM UTC
    # 2:00 PM IST = 8:30 AM UTC  
    # 9:00 PM IST = 3:30 PM UTC
    - cron: '30 2,8,15 * * *'
  
  # Optional: Allow manual trigger from GitHub UI
  workflow_dispatch:

jobs:
  update_resume:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager
        
    - name: Install Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Run update script
      env:
        NAUKRI_USERNAME: ${{ secrets.NAUKRI_USERNAME }}
        NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
      run: python ResumeAutomate.py
      # The script now exits with code 1 on failure, which will cause this step to fail
        
    - name: "Upload screenshots and logs (always run even on failure)"
      if: always()  # Run this step regardless of whether previous steps succeeded or failed
      uses: actions/upload-artifact@v3@b8c1b1d42c2b1d0c4604a9d0a1bbd7f5f9e8d2d6
      with:
        name: debug-artifacts-${{ github.run_id }}
        path: |
          *.png
          *.log
        retention-days: 5